---
development:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: squash
  password: squash
  database: squash_development
test:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: squash
  password: squash
  database: squash_test
production:
  adapter: postgresql
  encoding: utf8
  host: localhost
  username: squash
  password: squash
  database: squash_production
  pool: 30
